### ISSUE TITLE
权限组的配置

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#1]
需要开启以下权限：/tpa，/homes，/back，/list，/skull，/skin，/tps，/msg，/menu，/res，/warp，/afk等（欢迎补充）
权限节点我正在找，会在这里更新。
欢迎大家一起寻找相关权限节点。

**Comment by 0rikka0** [comment]
essentials系列：

    - essentials.back
    - essentials.build
    - essentials.home
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.spawn
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.warp.*
    - essentials.world.*
    - essentials.world.world_the_end
    - essentials.worlds.world
    - essentials.afk
    - essentials.list
    - essentials.help 
    - essentials.skull.others
    - essentials.msg
    - essentials.msg.color
    - essentials.msg.url
    - essentials.tps
    - essentials.me

欢迎补充

已写入builder组

**Comment by 0rikka0** [comment]
皮肤插件skinsrestorer系列：

    -skinsrestorer.command
    -skinsrestorer.command.set
    -skinsrestorer.command.set.url
    -skinsrestorer.command.clear
    -skinsrestorer.command.gui
    -skinsrestorer.command.update
    -skinsrestorer.playercmds

欢迎补充

已写入builder组

**Comment by 0rikka0** [comment]
箱子菜单chestcommands系列：

    - chestcommands.open.cd.yml
    - chestcommands.open.example.yml
    - chestcommands.open.menu.yml

欢迎补充

已写入builder组

**Comment by 0rikka0** [comment]
多世界multiverse-core系列：

    - multiverse.core.spawn.self
    - multiverse.teleport.*

欢迎补充

已写入builder组

**Comment by 0rikka0** [comment]
箱子商店quickshop系列：

    - quickshop.create.buy
    - quickshop.create.changeprice
    - quickshop.create.double
    - quickshop.create.sell
    - quickshop.use

欢迎补充

已写入builder组

**Comment by 0rikka0** [comment]
- player
    - playmoresounds.player
    - playmoresounds.sound.arrowhit
    - playmoresounds.sound.bedenter
    - playmoresounds.sound.bedleave
    - playmoresounds.sound.changehotbar
    - playmoresounds.sound.changelevel
    - playmoresounds.sound.craftingextract
    - playmoresounds.sound.furnaceextract
    - playmoresounds.sound.handhit
    - playmoresounds.sound.inventoryclick
    - playmoresounds.sound.joinserver
    - playmoresounds.sound.joinserver.listen
    - playmoresounds.sound.leaveserver
    - playmoresounds.sound.leaveserver.listen
    - playmoresounds.sound.playerachievement
    - playmoresounds.sound.playerchat
    - playmoresounds.sound.playercommand
    - playmoresounds.sound.playerdeath
    - playmoresounds.sound.playerdrop
    - playmoresounds.sound.playerflight
    - playmoresounds.sound.playerflightstop
    - playmoresounds.sound.playerteleport
    - playmoresounds.sound.regionenter
    - playmoresounds.sound.regionleave
    - playmoresounds.sound.swordhit
    - playmoresounds.sounds.radius.hide.invisible

**Comment by baysonfox** [comment]
全部权限已经被添加到luckperms的default组 老文件还未被移除
