### ISSUE TITLE
多世界管理混乱

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#12]
服务器内存在过多世界，大多数作用不明，对管理造成较大阻碍。
急需与其他管理确认这些世界的作用，并及时删除无用世界。

已定义：

      生存世界取名为：world
      创造世界取名为：creative
    出生点置于world中

附上mv list查询结果：

    30.05 01:00:47 [Server] INFO §7DIM7 - UNLOADED
    30.05 01:00:47 [Server] INFO §f1world§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §f1muse§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §fDIM-1§f§f - §cNETHER
    30.05 01:00:47 [Server] INFO §fDIM1§f§f - §bTHE_END
    30.05 01:00:47 [Server] INFO §f1flat§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §fflat§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §fworld§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §f1game§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §f1rpg§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §fsurv§f§f - §aNORMAL
    30.05 01:00:47 [Server] INFO §d====[ Multiverse World List ]====

**Comment by baysonfox** [comment]
世界已经被删除 但是玩家登陆出现问题
正在修复

**Comment by 0rikka0** [comment]
重写插件配置文件，已经修复
多世界配置完成
