### ISSUE TITLE
服务器管理

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#14]
1.增加op数量
2.删除无用插件，寻找bug
3.观察在线人数，考虑换vps

**Comment by baysonfox** [comment]
> 1.增加op数量
> 2.删除无用插件，寻找bug
> 3.观察在线人数，考虑换vps

针对VPS这一块几乎可以说是必然的 在多玩家的情况下TPS会大幅度下降
而且不排除有超开的嫌疑 tab显示的内存不太对劲

**Comment by 0rikka0** [comment]
需要一到两天的测试以及管理群讨论
预算大概300

op需要增加吗

**Comment by baysonfox** [comment]
300啊 有点呛 可以试试 可惜就是要做淘宝战士了
op的话我觉得需要增加2-3个

**Comment by 0rikka0** [comment]
op就在管理群中招吧，人选后台群中讨论
