### ISSUE TITLE
menu菜单的配置

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#2]
需要通过menu实现的功能在这里更新。

**Comment by 0rikka0** [comment]
mod物品的获取（点击获取）：mod名-物品名-id

    - 东方女仆前置mod-记忆中的幻想乡-patchouli:guide_book

**Comment by baysonfox** [comment]
可能会添加一个新的菜单来实现这个功能.

**Comment by 0rikka0** [comment]
初期菜单已完成
功能：传送到world/creative世界，回家，获得物品`东方女仆前置mod-记忆中的幻想乡-patchouli:guide_book`
配置文件已上传到服务端
