### ISSUE TITLE
生存/创造世界的制作和分离

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#8]
-生成生存世界和创造世界
-实现背包隔离
-实现跨世界传送

**Comment by baysonfox** [comment]
需要知道服务器内现在使用的插件

**Comment by 0rikka0** [comment]
应该是[多世界]Multiverse-Core-2.5

**Comment by baysonfox** [comment]
> 应该是[多世界]Multiverse-Core-2.5

那就可以使用Multiverse-Inventory来隔离背包了
跨世界传送可以使用stargate或者直接使用mv tp
生存世界和创造世界可以使用mv modify set mode creative/survival 解决

**Comment by 0rikka0** [comment]
跨世界传送可以warp，但不知道背包隔离有没有作用
其实我更推荐用menu实现跨世界传送
附上含有世界传送功能的menu写法

    menu-settings:
      name: "&1&l\u4E3B\u83DC\u5355"
      command: menu
      rows: 3
    tp-world:
      POSITION-X: 1
      POSITION-Y: 1
      COMMAND: 'console: mv tp {player} world'
      NAME: "&b\u4F20\u9001:\u4E3B\u4E16\u754C"
      ID: 42
      DATA-VALUE: 0
      AMOUNT: 1
      KEEP-OPEN: false
    tp-zy:
      POSITION-X: 2
      POSITION-Y: 1
      COMMAND: 'console: mv tp {player} zy'
      NAME: "&b\u4F20\u9001:\u8D44\u6E90\u4E16\u754C"
      ID: 41
      DATA-VALUE: 0
      AMOUNT: 1
      KEEP-OPEN: false

**Comment by 0rikka0** [comment]
暂时定义：
生存世界是world（目前出生点，主世界所在）
创造世界是create
麻烦做一下背包隔离（我不会orz）

**Comment by 0rikka0** [comment]
已放入背包隔离插件[背包隔离]Multiverse-Inventories-2.5.0-SNAPSHOT

**Comment by 0rikka0** [comment]
背包隔离配置完成
