### ISSUE TITLE
开服后gamerule配置

### ISSUE THREAD

**Issue by 0rikka0** [DD-Union/DD-Union-Server#9]
1.关闭火焰蔓延
2.关闭死亡掉落
3.关闭生物爆炸地形破坏

**Comment by 0rikka0** [comment]
ban ZomBie、Bai_Yu007、ZomBie_Fish
这是拔刀剑mod的一个bug，会给这三个玩家op权限

**Comment by baysonfox** [comment]
> ban ZomBie、Bai_Yu007、ZomBie_Fish

已经BAN

**Comment by baysonfox** [comment]
> 1.关闭火焰蔓延
> 2.关闭死亡掉落
> 3.关闭生物爆炸地形破坏

这个是需要根据世界设置的吗？

**Comment by 0rikka0** [comment]
我觉得直接全服吧，主要是防止卡服和出各种问题
mod服就以玩mod为主，原版生存降低一点难度比较好

**Comment by baysonfox** [comment]
搞定
